server:
  port: 80
  compression:
     enabled: true
     mime-types: text/html,text/xml,text/plain,text/css,application/json,application/javascript,image/svg+xml,application/x-font-ttf,application/x-font-truetype,application/x-font-opentype,application/vnd.ms-fontobject,application/font-sfnt  

mongodb:
  uri: mongodb://localhost/vision

spring:
  resources:
    cache-period: 31556926

logging:
  level:
    org.springframework: WARN
    org.mongodb: WARN
    org.apache: WARN
    ch: WARN
  file: ./app.log    